more tweaks

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,7 +4,7 @@
 # @author    Volker Theile <volker.theile@openmediavault.org>
 # @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
 # @copyright Copyright (c) 2009-2013 Volker Theile
-# @copyright Copyright (c) 2013-2015 OpenMediaVault Plugin Developers
+# @copyright Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -30,6 +30,11 @@ case "$1" in
         SERVICE_XPATH_NAME="minidlna"
         SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
 
+        if [ -z "${2}" ]; then
+            deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
+            deb-systemd-invoke stop ${SERVICE_XPATH_NAME} >/dev/null || true
+        fi
+
         if ! omv_config_exists "${SERVICE_XPATH}"; then
             omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
             omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
@@ -37,15 +42,9 @@ case "$1" in
             omv_config_add_element "${SERVICE_XPATH}" "port" "8200"
             omv_config_add_element "${SERVICE_XPATH}" "strict" "0"
             omv_config_add_element "${SERVICE_XPATH}" "tivo" "0"
-            omv_config_add_element "${SERVICE_XPATH}" "shares"
-        fi
-
-        if ! omv_config_exists "${SERVICE_XPATH}/loglevel"; then
-            omv_config_add_element "${SERVICE_XPATH}" "loglevel" "error"
-        fi
-
-        if ! omv_config_exists "${SERVICE_XPATH}/rootcontainer"; then
             omv_config_add_element "${SERVICE_XPATH}" "rootcontainer" "."
+            omv_config_add_element "${SERVICE_XPATH}" "shares"
+            omv_config_add_element "${SERVICE_XPATH}" "loglevel" "error"
         fi
 
         echo "Add ${SERVICE_XPATH_NAME} user to group: users"
@@ -69,5 +68,7 @@ case "$1" in
         exit 1
     ;;
 esac
+
+#DEBHELPER#
 
 exit 0
